### ISSUE TITLE
Action should perform (an optional) login to GCR

### ISSUE THREAD

**Issue by dimw** [sendinblue/build-and-push-action#2]
Currently, the login to GCR (GCP) has to be performed in advance using the `setup-gcloud` action by performing e.g.:
```yaml
-  uses: google-github-actions/setup-gcloud@master
   with:
     project_id: 'my-project-1234'
     service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
```
However, since the service account key is usually already stored in GitHub Secrets, the [JSON key file](https://cloud.google.com/container-registry/docs/advanced-authentication) could be used to perform the login. Which would make the `setup-gcloud` step obsolete and also facilitate the workflow by reducing the number of dependencies.
